### PR TITLE
Security middleware: add Referrer-Policy header option

### PR DESCRIPTION
**Pull request by ripexz**
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

### CODE REVIEW

**Comment by aodhom** [comment]
Did this get pinged from a specific issue? Pentest etc?

Should probably consider adding it as a standard header in HA if its causing cross product issues.

**Comment by ripexz** [comment]
> Huh, I never knew of Referrer-Policy. Would this remove the need for `rel="noreferrer"` on outbound links in our apps?

Basically yeah, if that is the default you can set it on the headers and then if you *do* want to send ref - set it on the link itself 🤔

**Comment by adam-lynch** [comment]
Since we never check referrer in our apps, maybe we should add this header to all HTML responses. That's easily done in S3, CloudFront, maybe HAProxy

**Comment by adam-lynch** [comment]
I'll add an L10 issue

**Comment by JaTochNietDan** [comment]
> Since we never check referrer in our apps, maybe we should add this header to all HTML responses. That's easily done in S3, CloudFront, maybe HAProxy

Agreed that seems like a good idea to me as well.

**Comment by JaTochNietDan** [comment]
One note though is that we might need an exception in there for help docs, because some people might want referrer links in their help docs. I guess it would depend on their security settings and such.

**Pull request merged**
