### PR TITLE
Port StripFileExtensions from Desk

### PR DESCRIPTION
**Pull request by gangleri**
Copy StripFileExtensions from Desk so that it can be used in Spaces
and other projects

- Add Sanitize middleware
- Add tests
- Update Gopkg.lock to include echo so tests can be run

### CODE REVIEW

**Comment by Carpetsmoker** [comment]
I don't think we should port this to be honest. It's an ugly hack. I have never happy with it in Desk either, and the only reason we added it in Desk was because we were supposed to move away from adding `.json` to all our endpoints.

It would be better to either simply not use `.json` (easiest), or fix echo's router or swap it for something else (harder).

**Comment by ready4god2513** [comment]
We don't get the choice to not use `.json`.  It's something that's been decided on.  So now we need to support it everywhere.

**Comment by Carpetsmoker** [comment]
Then someone should fix the echo router. Adding middlewares is very annoying because it adds two entries to the stack trace on any error. It's already almost two pages in a full-screen terminal on my screen. Every time I have an error I need to scroll up. Very annoying when trying to fix stuff.

The only reason my PR got reverted is because it had a bug, so if someone fixes that, then we can just use the echo router.

**Comment by ready4god2513** [comment]
Sure. We can do that. But the spaces team needs this in the mean time.

**Comment by gangleri** [comment]
Closing this PR as it's been replaced by https://github.com/Teamwork/echoutil/pull/11

**Pull request closed without merging**
